name: Build & Release

on:
  push:
    branches: [patch/*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build & Release
        uses: crazidev/flutter-shorebird-action@v1
        with:
          FLUTTER_VERSION: "3.41.8"
          FLUTTER_BUILD_APK: true
          FLUTTER_BUILD_AAB: true
          FLUTTER_BUILD_WEB: false

          SHOREBIRD_RELEASE: false
          SHOREBIRD_BUILD_IOS: false
          SHOREBIRD_BUILD_ANDROID: true

          SHOREBIRD_PATCH: true
          SHOREBIRD_PATCH_RELEASE_VERSION: "1.0.1+1"
          SHOREBIRD_PATCH_ANDROID: true
          SHOREBIRD_PATCH_IOS: false
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD }}